### Root path / Introduction path
GET https://edusync-fyp-server.vercel.app/

### Create a new user
GET https://edusync-fyp-server.vercel.app/api/users/create?username=talib&email=talib@email.com&password=talib
GET https://edusync-fyp-server.vercel.app/api/users/create?username=subhan&email=subhan@email.com&password=subhan
GET https://edusync-fyp-server.vercel.app/api/users/create?username=wasif&email=wasif@email.com&password=wasif


### Duplicate user (same as already created)
GET https://edusync-fyp-server.vercel.app/api/users/create?username=wasif&email=wasif@email.com&password=wasif

### Read all users
GET https://edusync-fyp-server.vercel.app/api/users/all


### Read a user by email
GET https://edusync-fyp-server.vercel.app/api/users/read?email=subhan@email.com


### Update a user (username update)
GET https://edusync-fyp-server.vercel.app/api/users/update?email=talib@email.com&username=talibabbas&password=talib


### Delete a user by email (subhan)
GET https://edusync-fyp-server.vercel.app/api/users/delete?email=subhan@email.com


### Verify user deletion (by checking all users)
GET https://edusync-fyp-server.vercel.app/api/users/all

### Delete another user (talib)
GET https://edusync-fyp-server.vercel.app/api/users/delete?email=talib@email.com

### Verify user deletion (by checking all users)
GET https://edusync-fyp-server.vercel.app/api/users/all

### Delete another user (wasif)
GET https://edusync-fyp-server.vercel.app/api/users/delete?email=wasif@email.com

### Verify user deletion (by checking all users)
GET https://edusync-fyp-server.vercel.app/api/users/all
